"use client";

import Link from "next/link";
import { ChevronRight, CircleHelp, ExternalLink, Landmark, MessageCircleQuestion, ShieldCheck } from "lucide-react";
import { useI18n } from "@/components/providers/i18n-provider";
import { usePersonalization } from "@/components/providers/personalization-provider";
import { PageHeading } from "@/components/shared/page-heading";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LEGAL_DOCUMENTS, LEGAL_FAQS } from "@/lib/legal";

export function LegalCenter() {
  const { t } = useI18n();
  const { settings } = usePersonalization();
  return <>
    <PageHeading eyebrow={t("legal.eyebrow", "Правовой центр")} title={t("legal.title", "Документы и правовая информация")} description={t("legal.description", "Условия обслуживания, раскрытие информации и понятные ответы на частые вопросы о работе {bank}.", { bank: settings.brandName })} />
    <Card className="glow-hero metric-glow relative mb-4 overflow-hidden border-primary/25"><CardContent className="relative z-10 grid gap-5 p-5 sm:p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-primary/12 px-3 py-1 text-[10px] font-bold text-primary"><ShieldCheck className="size-3.5" />{t("legal.disclosure.badge", "Прозрачное обслуживание")}</span><h2 className="mt-4 text-xl font-bold tracking-tight">{t("legal.disclosure.title", "Важная информация — без мелкого шрифта")}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{t("legal.disclosure.description", "Это демонстрационный интерфейс. Материалы показывают структуру юридического центра и не являются публичной офертой или юридической консультацией.")}</p></div><Link href="/bank" className="inline-flex h-10 w-fit items-center gap-2 rounded-xl border bg-background/55 px-4 text-sm font-semibold outline-none transition-colors hover:bg-secondary focus-visible:ring-2 focus-visible:ring-ring">{t("legal.aboutBank", "О банке")}<ExternalLink className="size-4" /></Link></CardContent></Card>
    <div className="grid auto-rows-fr gap-3 md:grid-cols-2 xl:grid-cols-3">{LEGAL_DOCUMENTS.map((document) => { const Icon = document.icon; return <Link key={document.slug} href={`/settings/legal/${document.slug}`} className="h-full outline-none focus-visible:ring-2 focus-visible:ring-ring"><Card className="group h-full min-h-40 p-5 transition-[border-color,background-color,box-shadow] hover:border-primary/25 hover:bg-secondary/35 hover:shadow-[0_0_28px_-22px_var(--glow-lime)]"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4" /></span><ChevronRight className="size-4 text-muted-foreground transition-colors group-hover:text-primary" /></div><h2 className="mt-4 font-bold">{t(document.titleKey)}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{t(document.summaryKey)}</p><p className="mt-3 font-mono text-[9px] uppercase tracking-[0.12em] text-muted-foreground">{t("legal.updated", "Обновлено")} · {document.updated}</p></Card></Link>; })}</div>
    <Card className="mt-4"><CardHeader><CardTitle className="flex items-center gap-2"><MessageCircleQuestion className="size-5 text-primary" />{t("legal.faq.title", "Вопросы и ответы")}</CardTitle><p className="text-sm text-muted-foreground">{t("legal.faq.description", "Коротко о документах, данных, операциях и безопасности.")}</p></CardHeader><CardContent className="divide-y">{LEGAL_FAQS.map((id) => <details key={id} className="group py-1"><summary className="flex min-h-14 list-none items-center gap-3 rounded-xl px-2 text-sm font-bold outline-none transition-colors hover:bg-secondary/45 focus-visible:ring-2 focus-visible:ring-ring"><CircleHelp className="size-4 shrink-0 text-primary" /><span className="flex-1">{t(`legal.faq.${id}.q`)}</span><ChevronRight className="size-4 text-muted-foreground transition-transform group-open:rotate-90" /></summary><p className="px-9 pb-4 text-sm leading-6 text-muted-foreground">{t(`legal.faq.${id}.a`, undefined, { bank: settings.brandName })}</p></details>)}</CardContent></Card>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><Link href="/support" className="glass-panel flex min-h-20 items-center gap-3 rounded-2xl border bg-background/35 p-4 outline-none transition-colors hover:bg-secondary/45 focus-visible:ring-2 focus-visible:ring-ring"><MessageCircleQuestion className="size-5 text-primary" /><span><span className="block font-bold">{t("legal.ask.title", "Задать вопрос банку")}</span><span className="text-xs text-muted-foreground">{t("legal.ask.description", "Поддержка поможет найти нужный документ")}</span></span></Link><Link href="/settings/legal/requisites" className="glass-panel flex min-h-20 items-center gap-3 rounded-2xl border bg-background/35 p-4 outline-none transition-colors hover:bg-secondary/45 focus-visible:ring-2 focus-visible:ring-ring"><Landmark className="size-5 text-primary" /><span><span className="block font-bold">{t("legal.requisites.short", "Реквизиты банка")}</span><span className="text-xs text-muted-foreground">{t("legal.requisites.description", "Регистрационные данные демонстрационного банка")}</span></span></Link></div>
  </>;
}
